services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db
    restart: always 
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: fran21$23
       POSTGRES_DB: inventario
    ports:
      - "5432:5432"
    volumes: 
      - "pgdata:/var/lib/postgresql/data"

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db 
    restart: always
volumes:
 pgdata:
